export const INITIAL_MOCK_DATA = {
  orderNum: "7829",
  phone: "(555) 123-4567",
  email: "john.doe@example.com",
  orderType: "DELIVERY",
  orderId: "UBW-9921D",
  currentPage: 1,
  totalPages: 3,
  time: "14:30",
  date: "10/12/2023",
  itemName: "Spicy Chicken Sandwich",
  modifier1: "- No Mayo",
  modifier2: "- Add Extra Pickles",
  modifier3: "- Toasted Bun",
  customer: "Jane Doe",
  quantity: 2,
  indent: "  ",
  text: "No onions, extra pickles",
  callnum: "102",
  readyTime: "12:45 PM",
  paid: true,
  onlineId: "UBER-5829",
  onlineProvider: "UberEats",
  guest: "Bob",
  guests: "Alice, Bob",
  name: "Jane",
  guestCount: 2,
  originalReadyTime: "12:30 PM",
  vprinterName: "Kitchen 1",
  alternate: "Kitchen 2",
  refcode: "ABC-987",
  memo: "Leave at door",
  created: "10/12/2023",
  owner: "John Smith",
  orderClass: "Delivery",
  
  // New receipt data
  restaurantName: "BURGERS & CO.",
  restaurantAddress: "123 Main Street",
  restaurantPhone: "(555) 999-0000",
  cashier: "Sarah T.",
  item1Qty: "2",
  item1Name: "Classic Burger",
  item1Price: "$18.00",
  item1Mod1: "  - No Onions",
  item1Mod2: "  - Add Bacon",
  item2Qty: "1",
  item2Name: "Large Fries",
  item2Price: "$4.50",
  subtotal: "$22.50",
  tax: "$1.86",
  tip: "$4.00",
  total: "$28.36"
};
