export const defaultReceipt = {
    "header": [
        {"type": "token",    "value": "center"},
        {"type": "token",    "value": "wide"},
        {"type": "variable", "value": "restaurantName"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "narrow"},
        {"type": "variable", "value": "restaurantAddress"},
        {"type": "newline",  "value": "10"},
        {"type": "variable", "value": "restaurantPhone"},
        {"type": "newline",  "value": "10"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "left"},
        {"type": "hr",       "value": "*"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Order #:    "},
        {"type": "variable", "value": "orderNum"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Date:       "},
        {"type": "variable", "value": "date"},
        {"type": "text",     "value": " "},
        {"type": "variable", "value": "time"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Cashier:    "},
        {"type": "variable", "value": "cashier"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Type:       "},
        {"type": "variable", "value": "orderType"},
        {"type": "newline",  "value": "10"},
        {"type": "hr",       "value": "*"},
        {"type": "newline",  "value": "10"}
    ],
    "guest": [
        {"type": "text",     "value": "Customer:   "},
        {"type": "variable", "value": "customer"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Email:      "},
        {"type": "variable", "value": "email"},
        {"type": "newline",  "value": "10"},
        {"type": "hr",       "value": "*"},
        {"type": "newline",  "value": "10"}
    ],
    "item": [
        {"type": "variable", "value": "item1Qty"},
        {"type": "text",     "value": " x "},
        {"type": "variable", "value": "item1Name"},
        {"type": "text",     "value": "                "},
        {"type": "variable", "value": "item1Price"},
        {"type": "newline",  "value": "10"}
    ],
    "modifier": [
        {"type": "token",    "value": "narrow"},
        {"type": "text",     "value": "  "},
        {"type": "variable", "value": "item1Mod1"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "  "},
        {"type": "variable", "value": "item1Mod2"},
        {"type": "newline",  "value": "10"},
        {"type": "variable", "value": "item2Qty"},
        {"type": "text",     "value": " x "},
        {"type": "variable", "value": "item2Name"},
        {"type": "text",     "value": "                    "},
        {"type": "variable", "value": "item2Price"},
        {"type": "newline",  "value": "10"}
    ],
    "footer": [
        {"type": "hr",       "value": "*"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Subtotal:                      "},
        {"type": "variable", "value": "subtotal"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Tax:                           "},
        {"type": "variable", "value": "tax"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Tip:                           "},
        {"type": "variable", "value": "tip"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "wide"},
        {"type": "text",     "value": "Total:         "},
        {"type": "variable", "value": "total"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "narrow"},
        {"type": "hr",       "value": "*"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "center"},
        {"type": "text",     "value": "Powered by Plum POS"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "left"},
        {"type": "token",    "value": "cutter"},
        {"type": "newline",  "value": "10"}
    ]
};

export const defaultLabel = {
    "header": [
        {"type": "token",    "value": "center"},
        {"type": "token",    "value": "wide"},
        {"type": "text",     "value": "#"},
        {"type": "variable", "value": "orderNum"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "narrow"},
        {"type": "token",    "value": "left"},
        {"type": "hr",       "value": "*"},
        {"type": "newline",  "value": "10"},
        {"type": "variable", "value": "phone"},
        {"type": "text",     "value": "                  "},
        {"type": "variable", "value": "orderType"},
        {"type": "newline",  "value": "10"},
        {"type": "variable", "value": "email"},
        {"type": "text",     "value": "           "},
        {"type": "variable", "value": "orderId"},
        {"type": "newline",  "value": "10"},
        {"type": "hr",       "value": "*"},
        {"type": "newline",  "value": "10"}
    ],
    "itemPage": [
        {"type": "text",     "value": "Item: "},
        {"type": "variable", "value": "currentPage"},
        {"type": "text",     "value": " of "},
        {"type": "variable", "value": "totalPages"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Time: "},
        {"type": "variable", "value": "time"},
        {"type": "newline",  "value": "10"},
        {"type": "text",     "value": "Date: "},
        {"type": "variable", "value": "date"},
        {"type": "newline",  "value": "10"},
        {"type": "hr",       "value": "*"},
        {"type": "newline",  "value": "10"}
    ], 
    "modifier": [
        {"type": "token",    "value": "wide"},
        {"type": "variable", "value": "itemName"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "narrow"},
        {"type": "variable", "value": "modifier1"},
        {"type": "newline",  "value": "10"},
        {"type": "variable", "value": "modifier2"},
        {"type": "newline",  "value": "10"},
        {"type": "variable", "value": "modifier3"},
        {"type": "newline",  "value": "10"}
    ],
    "footer": [
        {"type": "hr",       "value": "*"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "center"},
        {"type": "text",     "value": "Powered by Plum POS"},
        {"type": "newline",  "value": "10"},
        {"type": "token",    "value": "left"},
        {"type": "token",    "value": "black"},
        {"type": "token",    "value": "cutter"},
        {"type": "newline",  "value": "10"}
    ]
};
